### ISSUE TITLE
Possible to kill process but not auto restart?

### ISSUE THREAD

**Issue by ConorGarry** [YarikSOffice/venom#20]
This would an ideal tool for our QA team for testing events that happen after the process has been destroyed. Things like handling push notifications that trigger a cold start for instance.

When I kill process, it auto restarts. Is there a way to block the restart part of it?

**Comment by YarikSOffice** [comment]
@ConorGarry The library doesn't provide a way of doing this at the moment, unfortunately. 
I need to investigate whether it's doable. Anyway, I'll consider it as a feature candidate for the next version.

Thanks for your feedback and feature request!

**Comment by YarikSOffice** [comment]
Fixed via https://github.com/YarikSOffice/venom/pull/41
