### ISSUE TITLE
Update README.md to match current release

### ISSUE THREAD

**Issue by SimonMarquis** [YarikSOffice/venom#43]
And showcase the new kill vs restart feature.

- notification screenshot (and gif)
- code snippet for the configuration
- detail effects of both actions

Do you need some help to update those elements?

**Comment by YarikSOffice** [comment]
@SimonMarquis right, I'd appreciate any contribution to updating the README
Let me know if you want to take any of these points

**Comment by SimonMarquis** [comment]
I already did some screenshots/clip in PR #33.
I did not check out your PR, but I guess the behaviors where similar?

- screenshot: https://user-images.githubusercontent.com/1921278/172055445-544a46a0-e59d-4609-8acd-4cd3eca9bd8b.png
- clip: would have to be re-done

WDYT? I can start a draft PR

**Comment by YarikSOffice** [comment]
Let's split it into multiple PR, I'd appreciate it if you could create a PR for the screenshot and gif animation

**Comment by YarikSOffice** [comment]
@SimonMarquis thanks for your contribution 👍
